import { defineConfig } from 'wxt';

export default defineConfig({
    srcDir: 'src',
    modules: ['@wxt-dev/module-vue'],
    manifest: {
        name: 'PDD 店铺数据采集',
        description: '用于采集 PDD 商家后台店铺数据的浏览器插件',
        permissions: [
            'accessibilityFeatures.modify',
            'accessibilityFeatures.read',
            'activeTab',
            'alarms',
            'audio',
            'background',
            'bookmarks',
            'browsingData',
            'certificateProvider',
            'clipboardRead',
            'clipboardWrite',
            'contentSettings',
            'contextMenus',
            'cookies',
            'debugger',
            'declarativeContent',
            'declarativeNetRequest',
            'declarativeNetRequestWithHostAccess',
            'declarativeNetRequestFeedback',
            'dns',
            'desktopCapture',
            'documentScan',
            'downloads',
            'downloads.open',
            'downloads.ui',
            'enterprise.deviceAttributes',
            'enterprise.hardwarePlatform',
            'enterprise.networkingAttributes',
            'enterprise.platformKeys',
            'favicon',
            'fileBrowserHandler',
            'fileSystemProvider',
            'fontSettings',
            'gcm',
            'geolocation',
            'history',
            'identity',
            'identity.email',
            'idle',
            'loginState',
            'management',
            'nativeMessaging',
            'notifications',
            'offscreen',
            'pageCapture',
            'platformKeys',
            'power',
            'printerProvider',
            'printing',
            'printingMetrics',
            'privacy',
            'processes',
            'proxy',
            'readingList',
            'runtime',
            'scripting',
            'search',
            'sessions',
            'sidePanel',
            'storage',
            'system.cpu',
            'system.display',
            'system.memory',
            'system.storage',
            'tabCapture',
            'tabGroups',
            'tabs',
            'topSites',
            'tts',
            'ttsEngine',
            'unlimitedStorage',
            'vpnProvider',
            'wallpaper',
            'webAuthenticationProxy',
            'webNavigation',
            'webRequest',
            'webRequestBlocking'
        ],
        host_permissions: ['<all_urls>']
    },
    webExt: {
        disabled: true
    }
});
